# Generated by Django 3.1.7 on 2021-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=123456, max_length=6, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
